#!/usr/bin/env bash
set -euo pipefail

# Simple icon generator using base64 encoded minimal PNGs
# Creates placeholder icons for Tauri without requiring Python PIL

ICONS_DIR="src-tauri/icons"
mkdir -p "$ICONS_DIR"

echo "🎨 Generating placeholder icons for Tauri..."

# Minimal 32x32 blue PNG (base64 encoded)
# This is a simple solid blue square
cat > "$ICONS_DIR/32x32.png" << 'EOF' | base64 -d
iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAlwSFlz
AAAOxAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAABcSURB
VFiF7dSxDQAgDAPBz8AYjMEYsDgC0qWA9Lp8RQr5I1kkkkgkkUQSSSSSyH+TJJJIIolEEkkkkshH
k0QiiSQSSSSSyE+TRBJJJJJIJJFIIpFEfp0kkkgiiXwAd6YKMGRGvWAAAAAASUVORK5CYII=
EOF

echo "✓ Created $ICONS_DIR/32x32.png"

# For larger sizes, we can reuse the same image (Tauri will handle scaling)
cp "$ICONS_DIR/32x32.png" "$ICONS_DIR/128x128.png"
echo "✓ Created $ICONS_DIR/128x128.png"

cp "$ICONS_DIR/32x32.png" "$ICONS_DIR/128x128@2x.png"
echo "✓ Created $ICONS_DIR/128x128@2x.png"

# Create a minimal .ico file (Windows)
# This is a base64 encoded minimal valid .ico
cat > "$ICONS_DIR/icon.ico" << 'EOF' | base64 -d
AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAQAQAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAA
EOF

echo "✓ Created $ICONS_DIR/icon.ico"

# For .icns (macOS), create an empty placeholder
# Tauri can generate this from the PNGs during build
touch "$ICONS_DIR/icon.icns"
echo "✓ Created placeholder $ICONS_DIR/icon.icns"

echo ""
echo "✅ Icon generation complete!"
echo "💡 These are minimal placeholder icons."
echo "   To create custom icons, use: cargo install tauri-icon && tauri icon path/to/icon.png"
