#!/usr/bin/env python3
"""
Generate placeholder icons for Tauri desktop app
Creates simple colored squares with "CA" text as placeholders
"""

from PIL import Image, ImageDraw, ImageFont
import os

# Icon sizes to generate
ICON_SIZES = {
    '32x32.png': 32,
    '128x128.png': 128,
    '128x128@2x.png': 256,
}

def create_icon(size, output_path):
    """Create a simple icon with gradient background and text"""
    # Create image with gradient blue background
    img = Image.new('RGB', (size, size), color='#2563eb')
    draw = ImageDraw.Draw(img)

    # Draw a simple gradient effect
    for y in range(size):
        opacity = int(255 * (1 - y / size * 0.3))
        draw.rectangle([(0, y), (size, y+1)], fill=(37, 99, 235, opacity))

    # Add white circle background for text
    circle_radius = int(size * 0.7 / 2)
    circle_center = (size // 2, size // 2)
    circle_bbox = [
        circle_center[0] - circle_radius,
        circle_center[1] - circle_radius,
        circle_center[0] + circle_radius,
        circle_center[1] + circle_radius
    ]
    draw.ellipse(circle_bbox, fill='white')

    # Add "CA" text (ClientATS initials)
    try:
        # Try to use a system font
        font_size = int(size * 0.35)
        try:
            font = ImageFont.truetype("/System/Library/Fonts/Helvetica.ttc", font_size)
        except:
            try:
                font = ImageFont.truetype("/System/Library/Fonts/Arial.ttf", font_size)
            except:
                font = ImageFont.load_default()
    except:
        font = ImageFont.load_default()

    text = "CA"
    # Get text bounding box for centering
    bbox = draw.textbbox((0, 0), text, font=font)
    text_width = bbox[2] - bbox[0]
    text_height = bbox[3] - bbox[1]

    text_x = (size - text_width) // 2
    text_y = (size - text_height) // 2 - int(size * 0.05)  # Slight upward adjustment

    draw.text((text_x, text_y), text, fill='#2563eb', font=font)

    # Save
    img.save(output_path, 'PNG')
    print(f"✓ Created {output_path} ({size}x{size})")

def create_ico(source_png, output_path):
    """Create Windows .ico file from PNG"""
    img = Image.open(source_png)
    img.save(output_path, format='ICO', sizes=[(32, 32), (64, 64), (128, 128), (256, 256)])
    print(f"✓ Created {output_path}")

def main():
    # Create icons directory
    icons_dir = os.path.join(os.path.dirname(__file__), '../../src-tauri/icons')
    os.makedirs(icons_dir, exist_ok=True)

    print("🎨 Generating placeholder icons for Tauri...")

    # Generate PNG icons
    for filename, size in ICON_SIZES.items():
        output_path = os.path.join(icons_dir, filename)
        create_icon(size, output_path)

    # Create .ico for Windows
    ico_path = os.path.join(icons_dir, 'icon.ico')
    source_png = os.path.join(icons_dir, '128x128.png')
    create_ico(source_png, ico_path)

    # For macOS .icns, we'll create a note file
    icns_path = os.path.join(icons_dir, 'icon.icns')
    if not os.path.exists(icns_path):
        # Create a minimal valid icns file (empty)
        # Note: This won't be a proper icns but Tauri will generate it from PNGs
        with open(icns_path, 'w') as f:
            f.write('')
        print(f"⚠️  Created placeholder {icns_path} (will be generated by Tauri)")

    print("\n✅ Icon generation complete!")
    print("💡 Tip: Replace these with custom icons using 'tauri icon' command")
    print("   See: https://tauri.app/v1/guides/features/icons/")

if __name__ == '__main__':
    main()
